name: Pipeline API

on: 
  push: 
    branches:
      - release
  pull_request:
    branches:
      - release
  
jobs:
  pipeline:
    name: Pipeline    
    runs-on: ubuntu-latest
    environment:
      name: prd
    steps:
    - name: Checkout
      uses: actions/checkout@v2
   
    - name: Setup .NET CORE
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 3.1.x
        
    - name: Install AWS CLI
      id: install-aws-cli
      uses: unfor19/install-aws-cli-action@master
      with:
        version: 2

    - name: Install CodeArtifact
      run: |
        dotnet tool install -g AWS.CodeArtifact.NuGet.CredentialProvider
        dotnet codeartifact-creds install
        dotnet nuget locals all --clear
        dotnet codeartifact-creds configure set profile user1
        aws configure set region "us-east-1" --profile user1
        aws configure set aws_access_key_id ${{ secrets.AWS_ID }} --profile user1
        aws configure set aws_secret_access_key ${{ secrets.AWS_KEY }} --profile user1

    - name: Restore dependencies
      run: dotnet restore src/JaVisitei.Brasil.Api/*.csproj -s ${{ secrets.AWS_PACKAGE }}
  
    - name: Build
      run: dotnet build --configuration Release --no-restore ./src/JaVisitei.Brasil.Api
      
    - name: Tests
      run: dotnet test --no-restore --verbosity normal ./src/JaVisitei.Brasil.Test
      
    - name: Consume Nuget CodeArtifact
      run: dotnet add src/JaVisitei.Brasil.Api/JaVisitei.Brasil.Api.csproj package JaVisitei.Brasil.Nuget --version 1.0.2 --source ${{ secrets.AWS_PACKAGE }}

    - name: Publish
      run: dotnet publish -c Release -o '${{ github.workspace }}/app/publish'
      
    - uses: microsoft/variable-substitution@v1 
      with:
        files: '${{ github.workspace }}/app/publish/appsettings.json'
      env:
        Connection.Base: ${{ secrets.API_CONNECTION }}
        JWT.JWT_AUDIENCE: ${{ secrets.JWT_AUDIENCE }}
        JWT.JWT_ISSUER: ${{ secrets.JWT_ISSUER }}
        JWT.JWT_KEY: ${{ secrets.JWT_KEY }}
        JWT.JWT_SUBJECT: ${{ secrets.JWT_SUBJECT }}
        
    - name: Folders
      run: ls
      
    - name: Docker Hub
      uses: docker/login-action@v1
      with:
        username: ${{ secrets.DOCKER_HUB_USERNAME }}
        password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}
        
    - name: Docker Image
      run: docker build -f src/Dockerfile -t ${{ secrets.DOCKER_HUB_USERNAME }}/javisiteiapi:v1 .
      
    - name: Docker Push
      run: docker push ${{ secrets.DOCKER_HUB_USERNAME }}/javisiteiapi:v1