name: Pipeline API

on: 
  push: 
    branches:
      - release
  pull_request:
    branches:
      - release
      
jobs:
  pipeline:
    name: Pipeline    
    runs-on: ubuntu-latest
    environment:
      name: prd
    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - name: Setup .NET CORE
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 8.0.x

    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v1
      with:
        aws-access-key-id: ${{ secrets.AWS_ID }}
        aws-secret-access-key: ${{ secrets.AWS_KEY }}
        aws-region: "${{ secrets.AWS_REGION }}"
        
    - name: Docker Hub
      if: github.event_name != 'pull_request'
      uses: docker/login-action@v3
      with:
        username: ${{ secrets.DOCKER_HUB_USERNAME }}
        password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}
        
    # - name: Docker Image
    #   run: docker build --build-arg AWS_REGION="${{ secrets.AWS_REGION }}" --build-arg AWS_PACKAGE=${{ secrets.AWS_PACKAGE }} --build-arg AWS_ID=${{ secrets.AWS_ID }} --build-arg AWS_KEY=${{ secrets.AWS_KEY }} -f src/Dockerfile -t ${{ secrets.DOCKER_HUB_USERNAME }}/${{ secrets.DOCKER_HUB_REPOSITORY }}:v1 --no-cache .

    - name: Docker Push
      run: docker push ${{ secrets.DOCKER_HUB_USERNAME }}/${{ secrets.DOCKER_HUB_REPOSITORY }}:v1

    - name: Image digest
      run: echo ${{ steps.docker_build.outputs.digest }}